/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCreatePlaylistImport } from './routes/_authenticated/create-playlist'
import { Route as AuthenticatedPlaylistIdImport } from './routes/_authenticated/playlist.$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreatePlaylistRoute =
  AuthenticatedCreatePlaylistImport.update({
    path: '/create-playlist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPlaylistIdRoute = AuthenticatedPlaylistIdImport.update({
  path: '/playlist/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create-playlist': {
      preLoaderRoute: typeof AuthenticatedCreatePlaylistImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/': {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/playlist/$id': {
      preLoaderRoute: typeof AuthenticatedPlaylistIdImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([
    AuthenticatedCreatePlaylistRoute,
    AuthenticatedIndexRoute,
    AuthenticatedPlaylistIdRoute,
  ]),
  AboutRoute,
])

/* prettier-ignore-end */
